name: car_rental
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Firebase Core (required for all Firebase services)
  firebase_core: ^3.9.0

  # Firebase services (choose what you need)
  cloud_firestore: ^5.4.4    # Firestore database
  firebase_auth: ^5.4.1      # Authentication
  firebase_storage: ^12.3.3  # File uploads
  firebase_messaging: ^15.1.3 # Push notifications (optional)

  # Maps
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  #GET_IT {For Dependency injection and make calles of classes more effiecent }
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
