// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_kHJombkTKJkNqxvmxB0AYwz_vqiAMVY',
    appId: '1:732138107669:web:3c87f0954b2bbed2b7af1c',
    messagingSenderId: '732138107669',
    projectId: 'car-rental-01',
    authDomain: 'car-rental-01.firebaseapp.com',
    storageBucket: 'car-rental-01.firebasestorage.app',
    measurementId: 'G-W1GTPY2KQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZ2mhGqAo3s5NOfWV52yhcJWhtYRmUd0',
    appId: '1:732138107669:android:12a8cc63d58276e3b7af1c',
    messagingSenderId: '732138107669',
    projectId: 'car-rental-01',
    storageBucket: 'car-rental-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIANxYIEPHWhc7DPZWOAiGq3dPrRn0BZ8',
    appId: '1:732138107669:ios:d84dc960902ca6bab7af1c',
    messagingSenderId: '732138107669',
    projectId: 'car-rental-01',
    storageBucket: 'car-rental-01.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIANxYIEPHWhc7DPZWOAiGq3dPrRn0BZ8',
    appId: '1:732138107669:ios:d84dc960902ca6bab7af1c',
    messagingSenderId: '732138107669',
    projectId: 'car-rental-01',
    storageBucket: 'car-rental-01.firebasestorage.app',
    iosBundleId: 'com.example.carRental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_kHJombkTKJkNqxvmxB0AYwz_vqiAMVY',
    appId: '1:732138107669:web:674759a3489aba1eb7af1c',
    messagingSenderId: '732138107669',
    projectId: 'car-rental-01',
    authDomain: 'car-rental-01.firebaseapp.com',
    storageBucket: 'car-rental-01.firebasestorage.app',
    measurementId: 'G-RF16JXJRS6',
  );
}
